version: '3.1'

services:
  ruby-app:
    build:
      context: ./dockerfiles/
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Datad0g1
      POSTGRES_USER: pguser
    ports:
      - 5432:5432
    networks:
      - backend

  networks:
    - frontend
    - backend
